# Generated by Django 4.1.7 on 2023-03-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.IntegerField()),
                ('GuestJson', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='tNextCrawlerExecute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastExecute', models.DateTimeField(verbose_name='ultima execucao com retorno')),
                ('recordTotal', models.IntegerField(default=0)),
            ],
        ),
    ]
