# Generated by Django 4.1.7 on 2023-03-30 13:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tnextcrawlerexecute',
            managers=[
                ('NextExecute', django.db.models.manager.Manager()),
            ],
        ),
    ]
