# Generated by Django 4.1.7 on 2023-03-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0002_alter_tnextcrawlerexecute_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tnextcrawlerexecute',
            managers=[
            ],
        ),
    ]
