# Generated by Django 4.1.7 on 2023-03-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0003_alter_tnextcrawlerexecute_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnextcrawlerexecute',
            options={'managed': False},
        ),
    ]
