# Generated by Django 4.1.7 on 2023-03-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0004_alter_tnextcrawlerexecute_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tguests',
            table='appGET_crawler_tguests',
        ),
        migrations.AlterModelTable(
            name='tnextcrawlerexecute',
            table='appGET_crawler_tnextcrawlerexecute',
        ),
    ]
