# Generated by Django 4.1.7 on 2023-03-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0005_alter_tguests_table_alter_tnextcrawlerexecute_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnextcrawlerexecute',
            options={},
        ),
    ]
