# Generated by Django 4.1.7 on 2023-03-31 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0007_alter_tnextcrawlerexecute_lastexecute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnextcrawlerexecute',
            name='lastExecute',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 20, 57, 8, 751448, tzinfo=datetime.timezone.utc)),
        ),
    ]
