# Generated by Django 4.1.7 on 2023-03-31 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0008_alter_tnextcrawlerexecute_lastexecute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnextcrawlerexecute',
            name='lastExecute',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
