# Generated by Django 4.1.7 on 2023-04-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0011_taccess_terrorhandler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrorhandler',
            name='idError',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
