# Generated by Django 4.1.7 on 2023-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0014_alter_terrorhandler_iderror_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taccess',
            old_name='idAccess',
            new_name='refId',
        ),
        migrations.AddField(
            model_name='tguests',
            name='refId',
            field=models.IntegerField(default=0),
        ),
    ]
