# Generated by Django 4.1.7 on 2023-04-08 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGET_crawler', '0015_rename_idaccess_taccess_refid_tguests_refid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tAccessPoint',
            fields=[
                ('refId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('accessPointJson', models.JSONField()),
                ('insertDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'tAccessPoint',
            },
        ),
        migrations.AddField(
            model_name='taccess',
            name='stopConnection',
            field=models.BooleanField(default=True),
        ),
    ]
